= Software Development Kits (SDKs)

Knowing how to interact with a HTTP API directly is a good skill to have, but
sometimes the API team will have created a library/package/module written in
your programming language of choice, so that you don't have to bother. This is
know as a Software Development Kit, or an SDK for short. 

Theoretically, an SDK abstracts most of the transport layer specifics away
behind idiomatic code, taking care of authentication, URLs, methods, headers,
data formats, caching, retries, even HTTP status codes will be converted into
meaningful exceptions. The best SDKs will even turn validation errors into a
useful format. If that is the case for the specific API you are attempting to
integrate with, then you might be in luck, and perhaps you can skip a lot of
this book.

For example, we have not covered how Authentication works yet, and with a good
SDK you would not need to know. They will give you somewhere to pop in the
authentication details, in this instance an API key.

[source,javascript]
----
import Stripe from 'stripe';

const stripeApiKey = 'sk_test_4eC39HqLyjWDarjtT1zdp7dc';

const stripe = new Stripe(stripeApiKey);
const charge = await stripe.charges.create({
  amount: 2000,
  currency: 'usd',
  source: 'tok_amex',
  description: 'My First Test Charge',
});
----

Just as a good SDK can obfuscate the nitty gritty of the transport layer and
make it easier to get things done, a bad SDK might just get in the way and make
it harder to work with than just attacking the API directly. 

Much like any library/package/plugin, if it cannot do everything you require and
provides insufficient room for extension, it might easier to skip it and
interface directly with the API more directly (via HTTP, or whichever other
transport layer).

== Ensuring SDK Quality

To use an SDK for the API you are trying to integrate there needs to be an SDK
for the programming language you are using, and it needs to be well built. If
there is no official SDK, you can search around and try to find an unofficial
one.

Finding an SDK for the API you want to work with is usually a good thing, but
whether its official or unofficial, in-house or third-party, they all run the
risk of being useless, out-dated, unstable, or insecure. Abandonment can be a
big problem in the world of open-source, and best intensions lead to stagnated
software that might not even keep up with the latest API changes. Often I've
seen an SDK pointing at API v2 when the latest is API v3...

Assuming its up to date, let's make sure its good quality. To ensure the SDK is
of good quality, check for a few things.

- Are there lots of downloads/installs on the package repository?
- Does it have unit tests?
- Does it have documentation?
- Is that documentation any good?
- Is the code open-source and hosted somewhere useful like GitHub/GitLab/BitBucket?
- Are there loads of outstanding bug reports that are months old?
- Is anyone sending in pull requests and are they being reviewed or ignored?

For examples of great SDKs, again, check out
https://www.twilio.com/docs/libraries[Twilio], who do a fantastic job at
building SDKs. They have libraries/packages built for C#, Java, Node,
PHP, Python, Ruby, and JavaScript!

Another example is https://stripe.com/docs/api[Stripe]. They document
each SDK and its usage separately, with code examples that show how to
carry out certain tasks in those languages.

[source,javascript]
----
stripe.disputes.update(
  "dp_1AfYgX2eZvKYlo2CXQAAqDv7",
  {
    evidence: {
      customer_name: 'Elijah Williams',
      product_description: 'Comfortable cotton t-shirt',
      shipping_documentation: 'file_1BC7qO2eZvKYlo2CREONzM9U'
    }
  },
  function(err, dispute) {
    // asynchronously called
  }
);
----

Learning what can be sent in the `evidence` property here will probably be
documented like any other JavaScript library, but thats where another benefit of
SDKs come in: as you are working with code, your IDE should have a "Show Definition" option and you can glean more information about allowed options, validation rules, etc. 

If nothing useful shows up in the SDK docs or code, then popping over to the
general API Reference documentation will probably get you there, as often the payloads being passed in are just turned straight into JSON.

Assuming there is no decent SDK for the API you want to work with, let's keep
trucking and see if we can learn how to confidently interact with the API
ourselves over the next few chapters.

// TODO 
// Check for who owns it - Recently, opted out of using one particular tool because it was owned by a big evil telecom company 🤮
